[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
hello_world_transfer_hook = "98jF4sUxDMvoRdfotY3wn7yZzq5Ct7sRaMWdSgkFqTaH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
